# AstraFabric Render.com FREE TIER Configuration
# render.yaml - Free tier deployment with app factory

services:
  # Main web application - FREE TIER
  - type: web
    name: astrafabric-platform
    env: python
    # No plan specified = FREE tier
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app_factory:create_app()
    healthCheckPath: /health
    envVars:
      # Application Configuration
      - key: FLASK_ENV
        value: production
      - key: BASE_URL
        sync: false  # Set this in Render dashboard
      
      # Security Configuration (REQUIRED - Set in Render dashboard)
      - key: SECRET_KEY
        sync: false  # Generate a secure random key
      - key: ADMIN_PASSWORD
        sync: false  # Set a secure admin password
      
      # Database Configuration
      - key: DATABASE_URL
        fromDatabase:
          name: astrafabric-db
          property: connectionString
      
      # Payment Gateway Configuration (Set in Render dashboard)
      - key: NOWPAYMENTS_API_KEY
        sync: false
      - key: NOWPAYMENTS_HMAC_KEY
        sync: false
      - key: FLW_PUBLIC_KEY
        sync: false
      - key: FLW_SECRET_KEY
        sync: false
      - key: FLW_SECRET_HASH
        sync: false
      
      # Rate limiting falls back to memory on free tier
      - key: RATELIMIT_STORAGE_URL
        value: "memory://"
      
      # Application Settings (reduced for free tier)
      - key: GUNICORN_WORKERS
        value: "1"  # Reduced for free tier
      - key: GUNICORN_TIMEOUT
        value: "30"

  # PostgreSQL Database - FREE TIER
  - type: pgsql
    name: astrafabric-db
    # No plan specified = FREE tier (with limitations)
    databaseName: astrafabric
    user: astrafabric_user

# Note: Custom domains not available on free tier
# Use the provided .onrender.com domain
