# AstraFabric Render.com Deployment Configuration
# render.yaml - Render.com service configuration

services:
  # Main web application
  - type: web
    name: astrafabric-web
    env: python
    plan: starter  # $7/month
    buildCommand: pip install -r requirements.txt
    startCommand: python start-astrafabric.py
    healthCheckPath: /api/v1/health
    envVars:
      - key: ASTRAFABRIC_ENV
        value: production
      - key: ASTRAFABRIC_DOMAIN
        value: astrafabric.com
      - key: ASTRAFABRIC_CONTACT_PHONE
        value: "+2349043839065"
      - key: ASTRAFABRIC_WHATSAPP_1
        value: "+2349084824238"
      - key: ASTRAFRABRIC_WHATSAPP_2
        value: "+2349064376043"
      - key: ASTRAFABRIC_EMAIL
        value: "contact@astrafabric.com"
      - key: DATABASE_URL
        fromDatabase:
          name: astrafabric-db
          property: connectionString

  # Database service
  - type: pserv
    name: astrafabric-db
    env: postgresql
    plan: starter  # $7/month - managed PostgreSQL
    disk:
      name: astrafabric-data
      size: 10GB
      
  # Background worker (optional)
  - type: worker
    name: astrafabric-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python background-processor.py
    envVars:
      - key: ASTRAFABRIC_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: astrafabric-db
          property: connectionString

# Custom domains
domains:
  - astrafabric.com
  - www.astrafabric.com
  - api.astrafabric.com
